### ISSUE TITLE
To find/scrape: Anime by release date

### ISSUE THREAD

**Issue by euricaeris** [very-scary-scenario/unshuffle#7]
This time it'll be ideal to use the top rated shows. Another MAL scrape job?

**Comment by colons** [comment]
i think i'd favour 'most popular' over 'top rated', but yes

**Comment by colons** [comment]
…actually, no; we established last night that MAL's table view doesn't include exact start date. also, in most cases, we wouldn't want to penalise people for getting shows that aired in the same season in the wrong order. maybe anichart would be the best source for this one?
